CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "Accounts" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Password" text NULL,
        "EmailAddress" text NULL,
        "DefaultEmailIsVerified" boolean NOT NULL,
        "AccountId" text NULL,
        "CompanyName" text NULL,
        "PhoneNumber" text NULL,
        "CreationDate" timestamp without time zone NOT NULL,
        "AccountLogoUri" text NULL,
        "GeneralFallbackSubject" text NULL,
        "GeneralFallbackEmailTemplate" text NULL,
        "ApiKey" text NULL,
        "Active" boolean NOT NULL,
        "Locale" text NULL,
        "AccountType" integer NOT NULL,
        "PlanType" integer NOT NULL,
        "PaymentInterval" integer NULL,
        "HasUpgraded" boolean NOT NULL,
        "StripeCustomerId" text NULL,
        "CurrentPeriodEnd" timestamp without time zone NOT NULL,
        "IntroductionId" text NULL,
        "ShowSeenEnquiries" boolean NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "CategoryNestedThresholdTableRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "TableId" text NULL,
        "ValueMin" double precision NOT NULL,
        "ValueMax" double precision NOT NULL,
        "Range" boolean NOT NULL,
        "RowId" text NULL,
        "RowOrder" integer NOT NULL,
        "ItemId" text NULL,
        "ItemOrder" integer NOT NULL,
        "Category" text NULL,
        "Threshold" double precision NOT NULL,
        "TriggerFallback" boolean NOT NULL,
        CONSTRAINT "PK_CategoryNestedThresholdTableRows" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "ConversationHistoryRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ConversationId" text NULL,
        "Prompt" text NULL,
        "UserResponse" text NULL,
        "NodeId" text NULL,
        "NodeCritical" boolean NOT NULL,
        "NodeType" text NULL,
        "TimeStamp" timestamp without time zone NOT NULL,
        "AccountId" text NULL,
        CONSTRAINT "PK_ConversationHistoryRows" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "ConversationRecords" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "ConversationId" text NULL,
        "ResponsePdfId" text NULL,
        "TimeStamp" timestamp without time zone NOT NULL,
        "AccountId" text NULL,
        "IntentName" text NULL,
        "EmailTemplateUsed" text NULL,
        "Seen" boolean NOT NULL,
        "Name" text NULL,
        "Email" text NULL,
        "PhoneNumber" text NULL,
        "IntentId" text NULL,
        "IsDeleted" boolean NOT NULL,
        "IsFallback" boolean NOT NULL,
        "Locale" text NULL,
        "IsComplete" boolean NOT NULL,
        CONSTRAINT "PK_ConversationRecords" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "EmailVerifications" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AuthenticationToken" text NULL,
        "EmailAddress" text NULL,
        "AccountId" text NULL,
        CONSTRAINT "PK_EmailVerifications" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "FileAssets" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "FileId" text NULL,
        "RiskyNameStem" text NULL,
        "Extension" text NULL,
        "LocationKey" text NULL,
        CONSTRAINT "PK_FileAssets" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "Intents" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AreaIdentifier" text NULL,
        "AreaName" text NULL,
        "AreaDisplayTitle" text NULL,
        "Prologue" text NULL,
        "Epilogue" text NULL,
        "EmailTemplate" text NULL,
        "IsEnabled" boolean NOT NULL,
        "AccountId" text NULL,
        "AreaSpecificEmail" text NULL,
        "EmailIsVerified" boolean NOT NULL,
        "UseAreaFallbackEmail" boolean NOT NULL,
        "FallbackSubject" text NULL,
        "FallbackEmailTemplate" text NULL,
        "SendAttachmentsOnFallback" boolean NOT NULL,
        "SendPdfResponse" boolean NOT NULL,
        "IncludeDynamicTableTotals" boolean NOT NULL,
        "Subject" text NULL,
        CONSTRAINT "PK_Intents" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "Logos" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "AccountLogoFileId" text NULL,
        CONSTRAINT "PK_Logos" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "PercentOfThresholds" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "TableId" text NULL,
        "RowId" text NULL,
        "Threshold" double precision NOT NULL,
        "ValueMin" double precision NOT NULL,
        "ValueMax" double precision NOT NULL,
        "Range" boolean NOT NULL,
        "Modifier" double precision NOT NULL,
        "PosNeg" boolean NOT NULL,
        "RowOrder" integer NOT NULL,
        "TriggerFallback" boolean NOT NULL,
        "ItemOrder" integer NOT NULL,
        "ItemId" text NULL,
        "Category" text NULL,
        CONSTRAINT "PK_PercentOfThresholds" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "Sessions" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" text NULL,
        "AccountId" text NULL,
        "ApiKey" text NULL,
        "Expiration" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "SimpleSelectTableRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "TableId" text NULL,
        "Category" text NULL,
        "ValueMin" double precision NOT NULL,
        "ValueMax" double precision NOT NULL,
        "Range" boolean NOT NULL,
        "RowOrder" integer NOT NULL,
        CONSTRAINT "PK_SimpleSelectTableRows" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "SimpleThresholdTableRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "TableId" text NULL,
        "RowId" text NULL,
        "Threshold" double precision NOT NULL,
        "ValueMin" double precision NOT NULL,
        "ValueMax" double precision NOT NULL,
        "Range" boolean NOT NULL,
        "ItemName" text NULL,
        "RowOrder" integer NOT NULL,
        "TriggerFallback" boolean NOT NULL,
        CONSTRAINT "PK_SimpleThresholdTableRows" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "StaticFees" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Min" double precision NOT NULL,
        "Max" double precision NOT NULL,
        "FeeId" text NULL,
        "AccountId" text NULL,
        "IntentId" text NULL,
        CONSTRAINT "PK_StaticFees" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "StripeWebhookReceivedRecords" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "RecordId" text NULL,
        "PayloadSignature" text NULL,
        CONSTRAINT "PK_StripeWebhookReceivedRecords" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "Subscriptions" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "ApiKey" text NULL,
        "NumAreas" integer NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "TwoNestedSelectTableRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "TableId" text NULL,
        "ValueMin" double precision NOT NULL,
        "ValueMax" double precision NOT NULL,
        "Range" boolean NOT NULL,
        "RowId" text NULL,
        "RowOrder" integer NOT NULL,
        "ItemId" text NULL,
        "ItemOrder" integer NOT NULL,
        "Category" text NULL,
        "InnerItemName" text NULL,
        CONSTRAINT "PK_TwoNestedSelectTableRows" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "WidgetPreferences" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Placeholder" text NULL,
        "AccountId" text NULL,
        "LandingHeader" text NULL,
        "ChatHeader" text NULL,
        "SelectListColor" text NULL,
        "ListFontColor" text NULL,
        "HeaderColor" text NULL,
        "HeaderFontColor" text NULL,
        "FontFamily" text NULL,
        "OptionsHeaderColor" text NULL,
        "OptionsHeaderFontColor" text NULL,
        "ChatFontColor" text NULL,
        "ChatBubbleColor" text NULL,
        "ButtonColor" text NULL,
        "ButtonFontColor" text NULL,
        "WidgetState" boolean NOT NULL,
        CONSTRAINT "PK_WidgetPreferences" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "AttachmentRecords" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "FileId" text NULL,
        "IntentId1" integer NULL,
        CONSTRAINT "PK_AttachmentRecords" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AttachmentRecords_Intents_IntentId1" FOREIGN KEY ("IntentId1") REFERENCES "Intents" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "ConversationNodes" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "IntentId" text NULL,
        "AccountId" text NULL,
        "NodeId" text NULL,
        "Text" text NULL,
        "IsRoot" boolean NOT NULL,
        "IsCritical" boolean NOT NULL,
        "IsMultiOptionType" boolean NOT NULL,
        "IsTerminalType" boolean NOT NULL,
        "ShouldRenderChildren" boolean NOT NULL,
        "IsLoopbackAnchorType" boolean NOT NULL,
        "IsAnabranchType" boolean NOT NULL,
        "IsAnabranchMergePoint" boolean NOT NULL,
        "ShouldShowMultiOption" boolean NOT NULL,
        "IsDynamicTableNode" boolean NOT NULL,
        "IsMultiOptionEditable" boolean NOT NULL,
        "IsImageNode" boolean NOT NULL,
        "ImageId" text NULL,
        "OptionPath" text NULL,
        "ValueOptions" text NULL,
        "NodeType" text NULL,
        "DynamicType" text NULL,
        "NodeComponentType" text NULL,
        "ResolveOrder" integer NULL,
        "IsCurrency" boolean NOT NULL,
        "NodeChildrenString" text NULL,
        "NodeTypeCode" integer NOT NULL,
        "IntentId1" integer NULL,
        CONSTRAINT "PK_ConversationNodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ConversationNodes_Intents_IntentId1" FOREIGN KEY ("IntentId1") REFERENCES "Intents" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "PricingStrategyTableMetas" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "TableTag" text NULL,
        "PrettyName" text NULL,
        "TableType" text NULL,
        "TableId" text NULL,
        "AccountId" text NULL,
        "IntentId" text NULL,
        "ValuesAsPaths" boolean NOT NULL,
        "UseTableTagAsResponseDescription" boolean NOT NULL,
        "UnitId" integer NOT NULL,
        "IntentId1" integer NULL,
        CONSTRAINT "PK_PricingStrategyTableMetas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PricingStrategyTableMetas_Intents_IntentId1" FOREIGN KEY ("IntentId1") REFERENCES "Intents" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "StaticTablesMetas" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "TableOrder" integer NOT NULL,
        "Description" text NULL,
        "IntentId" text NULL,
        "AccountId" text NULL,
        "PerPersonInputRequired" boolean NOT NULL,
        "IncludeTotals" boolean NOT NULL,
        "IntentId1" integer NULL,
        CONSTRAINT "PK_StaticTablesMetas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StaticTablesMetas_Intents_IntentId1" FOREIGN KEY ("IntentId1") REFERENCES "Intents" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE TABLE "StaticTablesRows" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "RowOrder" integer NOT NULL,
        "Description" text NULL,
        "FeeId" integer NULL,
        "Range" boolean NOT NULL,
        "PerPerson" boolean NOT NULL,
        "TableOrder" integer NOT NULL,
        "IntentId" text NULL,
        "AccountId" text NULL,
        "StaticTablesMetaId" integer NULL,
        CONSTRAINT "PK_StaticTablesRows" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StaticTablesRows_StaticFees_FeeId" FOREIGN KEY ("FeeId") REFERENCES "StaticFees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StaticTablesRows_StaticTablesMetas_StaticTablesMetaId" FOREIGN KEY ("StaticTablesMetaId") REFERENCES "StaticTablesMetas" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_AttachmentRecords_IntentId1" ON "AttachmentRecords" ("IntentId1");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_ConversationNodes_IntentId1" ON "ConversationNodes" ("IntentId1");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_PricingStrategyTableMetas_IntentId1" ON "PricingStrategyTableMetas" ("IntentId1");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_StaticTablesMetas_IntentId1" ON "StaticTablesMetas" ("IntentId1");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_StaticTablesRows_FeeId" ON "StaticTablesRows" ("FeeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    CREATE INDEX "IX_StaticTablesRows_StaticTablesMetaId" ON "StaticTablesRows" ("StaticTablesMetaId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220716090947_Initial_Migration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220716090947_Initial_Migration', '3.1.23');
    END IF;
END $$;
