version: "3.9"

# a full working local app
services:
  stripe:
    container_name: Mock-Stripe
    image: stripe/stripe-mock:latest
    ports:
      - 12111-12112
    env_file:
      - ./local.env
    environment:
      - Palavyr_AWS__AwsS3ServiceUrl=http://host.docker.internal:4566
      - Palavyr_AWS__AwsSESServiceUrl=http://host.docker.internal:4566
      - Palavyr_DB__Host=http://host.docker.internal
      - Palavyr_AWS__PdfUrl=http://host.docker.internal:5603/pdf

  stripe-cli:
    image: stripe/stripe-cli
    container_name: Stripe-CLI
    command: "listen --device-name Palavyr --forward-to https://localhost:5001/api/payments/payments-webhook --skip-verify"
    env_file:
      - ./local.env
    environment:
      - Palavyr_AWS__AwsS3ServiceUrl=http://host.docker.internal:4566
      - Palavyr_AWS__AwsSESServiceUrl=http://host.docker.internal:4566
      - Palavyr_DB__Host=http://host.docker.internal
      - Palavyr_AWS__PdfUrl=http://host.docker.internal:5603/pdf
    depends_on:
      stripe:
        condition: service_completed_successfully

  postgres-server:
    image: postgres:14.1-alpine
    container_name: Database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password01!
    ports:
      - 5432:5432

  palavyr-server:
    image: paulegradie/palavyr:server-latest
    container_name: Server
    restart: always
    env_file:
      - ./local.env
    ports:
      - 5000:5000
    environment:
      - Palavyr_AWS__AwsS3ServiceUrl=http://host.docker.internal:4566
      - Palavyr_AWS__AwsSESServiceUrl=http://host.docker.internal:4566
      - Palavyr_DB__Host=http://host.docker.internal
      - Palavyr_AWS__PdfUrl=http://host.docker.internal:5603/pdf

  palavyr-web-frontend:
    image: paulegradie/palavyr:frontend-latest
    container_name: Frontend
    restart: always
    env_file:
      - ./ui/.env.frontend.development.docker
    ports:
      - 8080:8080

  palavyr-web-widget:
    image: paulegradie/palavyr:widget-latest
    container_name: Widget
    restart: always
    env_file:
      - ./ui/.env.widget.development.docker
    ports:
      - 3400:8080

  local-stack:
    image: localstack/localstack
    container_name: Aws-Localstack
    hostname: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,ses
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=default_access_key
      - AWS_SECRET_ACCESS_KEY=default_secret_key
    volumes:
      - ./init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock

  palavyr-data-migrator:
    image: paulegradie/palavyr:migrator-latest
    container_name: Data-Migrator
    env_file:
      - ./local.env
    environment:
      - Palavyr_AWS__AwsS3ServiceUrl=http://host.docker.internal:4566
      - Palavyr_AWS__AwsSESServiceUrl=http://host.docker.internal:4566
      - Palavyr_DB__Host=http://host.docker.internal
      - Palavyr_AWS__PdfUrl=http://host.docker.internal:5603/pdf
    ports:
      - 5100:5100
    depends_on:
      postgres-server:
        condition: service_healthy

  palavyr-pdf-server:
    image: paulegradie/palavyr:pdf-server-latest
    container_name: Server-PDF
    restart: always
    env_file:
      - ./pdf/.env.development
    ports:
      - 5603:5603

  palavyr-seq:
    image: datalust/seq:latest
    container_name: Seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 80:80
      - 5341:5341
      # volumes:
      # /path/to/seq/data:/data
