version: "3.9"

services:
  stripe:
    image: stripe/stripe-mock:latest
    ports:
      - 12111:12111
      - 12112:12112
    env_file:
      - ./local.env

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key sk_test_DOESNOTEXIST --device-name Palavyr --forward-to https://localhost:5001/api/payments/payments-webhook --forward-connect-to http://localhost:12111 --skip-verify"
    env_file:
      - ./local.env

  postgres-server:
    image: postgres:14.1-alpine
    container_name: Database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password01!
    ports:
      - 5432:5432
    volumes:
      - postgres-server:/var/lib/postgresql/data

  local-stack:
    image: localstack/localstack
    container_name: Aws-Localstack
    hostname: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,ses
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
    volumes:
      - ./init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-server:
    driver: local
