service: PalavyrServerless
app: palavyr-pdf-server
org: paulegradie

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

    # you can overwrite defaults here
    region: us-east-1

plugins:
    - serverless-express
    - serverless-webpack
    - serverless-offline

package:
    individually: true
    patterns:
        - assets/**

functions:
    Pdf-Server:
        handler: lambda.handler
        events:
            - http:
                  path: /{proxy+}
                  method: any

custom:
    webpack:
        webpackConfig: webpack.serverless.js

    serverless-offline:
        httpPort: 5603
