// <auto-generated />
using System;
using DashboardServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashboardServer.Data.Migrations.Dash
{
    [DbContext(typeof(DashContext))]
    [Migration("20200916081802_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Server.Domain.App.schema.DynamicTableMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrettyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ValuesAsPaths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("DynamicTableMetas");
                });

            modelBuilder.Entity("Server.Domain.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaDisplayTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Epilogue")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prologue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Server.Domain.ConversationNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fallback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeChildrenString")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueOptions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("ConversationNodes");
                });

            modelBuilder.Entity("Server.Domain.DynamicTables.SelectOneFlat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableTag")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueMax")
                        .HasColumnType("REAL");

                    b.Property<double>("ValueMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SelectOneFlats");
                });

            modelBuilder.Entity("Server.Domain.FileNameMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileNameMaps");
                });

            modelBuilder.Entity("Server.Domain.GroupMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Server.Domain.StaticFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StaticFees");
                });

            modelBuilder.Entity("Server.Domain.StaticTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerPerson")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StaticTablesMetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TableOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeeId");

                    b.HasIndex("StaticTablesMetaId");

                    b.ToTable("StaticTablesRows");
                });

            modelBuilder.Entity("Server.Domain.StaticTablesMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("TableOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("StaticTablesMetas");
                });

            modelBuilder.Entity("Server.Domain.WidgetPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShouldGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WidgetPreferences");
                });

            modelBuilder.Entity("Server.Domain.App.schema.DynamicTableMeta", b =>
                {
                    b.HasOne("Server.Domain.Area", null)
                        .WithMany("DynamicTableMetas")
                        .HasForeignKey("AreaId");
                });

            modelBuilder.Entity("Server.Domain.ConversationNode", b =>
                {
                    b.HasOne("Server.Domain.Area", null)
                        .WithMany("ConversationNodes")
                        .HasForeignKey("AreaId");
                });

            modelBuilder.Entity("Server.Domain.StaticTableRow", b =>
                {
                    b.HasOne("Server.Domain.StaticFee", "Fee")
                        .WithMany()
                        .HasForeignKey("FeeId");

                    b.HasOne("Server.Domain.StaticTablesMeta", null)
                        .WithMany("StaticTableRows")
                        .HasForeignKey("StaticTablesMetaId");
                });

            modelBuilder.Entity("Server.Domain.StaticTablesMeta", b =>
                {
                    b.HasOne("Server.Domain.Area", null)
                        .WithMany("StaticTablesMetas")
                        .HasForeignKey("AreaId");
                });
#pragma warning restore 612, 618
        }
    }
}
