CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "Accounts" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Password" text NULL,
        "EmailAddress" text NOT NULL,
        "DefaultEmailIsVerified" boolean NOT NULL,
        "AccountId" text NOT NULL,
        "CompanyName" text NULL,
        "PhoneNumber" text NULL,
        "CreationDate" timestamp without time zone NOT NULL,
        "AccountLogoUri" text NULL,
        "GeneralFallbackSubject" text NULL,
        "GeneralFallbackEmailTemplate" text NULL,
        "ApiKey" text NOT NULL,
        "Active" boolean NOT NULL,
        "Locale" text NOT NULL,
        "AccountType" integer NOT NULL,
        "PlanType" integer NOT NULL,
        "PaymentInterval" integer NULL,
        "HasUpgraded" boolean NOT NULL,
        "StripeCustomerId" text NULL,
        "CurrentPeriodEnd" timestamp without time zone NOT NULL,
        "IntroductionId" text NOT NULL,
        "ShowSeenEnquiries" boolean NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "Backups" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "LatestFullDbBackup" text NULL,
        CONSTRAINT "PK_Backups" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "EmailVerifications" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AuthenticationToken" text NULL,
        "EmailAddress" text NULL,
        "AccountId" text NULL,
        CONSTRAINT "PK_EmailVerifications" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "Sessions" (
        "SessionId" text NOT NULL,
        "AccountId" text NULL,
        "ApiKey" text NULL,
        "Expiration" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("SessionId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "StripeWebHookRecords" (
        "Id" text NOT NULL,
        "PayloadSignature" text NULL,
        CONSTRAINT "PK_StripeWebHookRecords" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    CREATE TABLE "Subscriptions" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "AccountId" text NULL,
        "ApiKey" text NULL,
        "NumAreas" integer NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211118083838_initial_migration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20211118083838_initial_migration', '3.1.13');
    END IF;
END $$;
