Transform: AWS::Serverless-2016-10-31

service: palavyr-pdf-service
app: palavyr-pdf-server
org: paulegradie

frameworkVersion: '2'

provider:
    name: aws
    runtime: dotnetcore3.1
    lambdaHashingVersion: 20201221

    # you can overwrite defaults here
    stage: dev
    region: us-east-1



Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Palavyr.API::Palavyr.API.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: Palavyr.API/bin/Release/netcoreapp3.1/Palavyr.API.zip
      Runtime: dotnetcore3.1
      MemorySize: 512
      Timeout: 20
      AutoPublishAlias: live
      Events:
        Api:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000

Outputs:
  ApiUrl:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
  Function:
    Value: !Ref Function