name: Build and Run Tests on pull request
on:
  pull_request:
    branches:
      - main

jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    name: Create next build number

    # Major Release Version
    env:
      MAJOR_VERSION: "0"

    # Lots of useful bits of information to use here
    # env:
    #   GITHUB_CONTEXT: ${{ toJson(github) }}

    outputs:
      version: ${{ steps.buildversion.outputs.version}}

    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Set Build Version
        id: buildversion
        run: |
          rawVersion="0.${{ steps.buildnumber.outputs.build_number }}-${{ github.event.pull_request.head.ref }}"
          echo ${rawVersion}
          echo ::set-output name=version::$(echo ${rawVersion} | tr "/" "-")

  build-and-test-server:
    name: Build and test server
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [generate-build-number]

    env:
      STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
      STRIPE_DEVICE_NAME: Palavyr

      Palavyr_AWS__AccessKey: ${{secrets.Palavyr_AWS__AccessKey}}
      Palavyr_AWS__SecretKey: ${{secrets.Palavyr_AWS__SecretKey}}
      Palavyr_AWS__Region: ${{secrets.Palavyr_AWS__Region}}
      Palavyr_ConnectionString: ${{secrets.Palavyr_ConnectionString}}
      Palavyr_Environment: ${{secrets.Palavyr_Environment}}
      Palavyr_JWT__SecretKey: ${{secrets.Palavyr_JWT__SecretKey}}
      Palavyr_STRIPE__SecretKey: ${{secrets.Palavyr_STRIPE__SecretKey}}

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: What I think the version number is
        run: |
          echo ==========================
          echo ${{ needs.generate-build-number.outputs.version }}
          echo ==========================

      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: |
          cd ./server
          dotnet restore

      - name: Build
        run: |
          cd ./server
          dotnet build --no-restore

      - name: Publish
        run: |
          cd ./server
          vers=${{ needs.generate-build-number.outputs.version }}
          dotnet publish -c Release /p:Version=${vers} --output ../solution_output

      # - name: Start Docker environment
      #   run: docker compose -f ./docker-compose.ci.yml up -d

      # - name: Pure Tests
      #   run: dotnet test ./solution_output/Palavyr.PureTests.dll --verbosity normal --no-restore

      # - name: Component Tests
      #   run: dotnet test ./solution_output/Palavyr.ComponentTests.dll --verbosity normal --no-restore

      # - name: Integration Tests
      #   run: dotnet test ./solution_output/Palavyr.IntegrationTests.dll --verbosity normal --no-restore

      - name: Delete the test dlls
        run: |
          ls -lath ./solution_output
          rm -rf ./solution_output/Palavyr.IntegrationTests*
          rm -rf ./solution_output/Palavyr.ComponentTests*
          rm -rf ./solution_output/Palavyr.PureTests*
          rm -rf ./solution_output/Test.Common*

      - name: Zip server into a package
        run: zip ./solution_output palavyr.server.${{ needs.generate-build-number.outputs.build_number }}.zip

  # build-frontend:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   name: Build frontend
  #   needs: [generate-build-number]

  #   steps:
  #     - name: Set up node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 12

  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Move into ui dir and install
  #       run: |
  #         cd ./ui
  #         npm ci

  #     - name: Move into ui dir and Build
  #       run: |
  #         cd ./ui
  #         npm run build

  #     - name: Move into ui dir and Zip the distribution
  #       run: |
  #         cd ./ui
  #         ls -lath
  #         zip -r palavyr-frontend.${{ needs.generate-build-number.outputs.build_number }}.zip ./dist-frontend
  #         mv palavyr-frontend.${{ needs.generate-build-number.outputs.build_number }}.zip ${{ github.workspace }}

  # build-widget:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   name: Build widget
  #   needs: [generate-build-number]

  #   steps:
  #     - name: Set up node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 12

  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Move into ui dir and install
  #       run: |
  #         cd ./ui
  #         npm ci

  #     - name: Move into ui dir and Build
  #       run: |
  #         cd ./ui
  #         npm run build-widget

  #     - name: Move into ui dir and Zip the distribution
  #       run: |
  #         cd ./ui
  #         ls -lath
  #         zip -r palavyr-widget.${{ needs.generate-build-number.outputs.build_number }}.zip ./dist-widget
  #         mv palavyr-widget.${{ needs.generate-build-number.outputs.build_number }}.zip ${{ github.workspace }}
